# Generated by Django 5.1.6 on 2025-03-07 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewee_name', models.CharField(max_length=255)),
                ('reviewee_role', models.CharField(choices=[('general', '一般'), ('manager', 'マネージャー'), ('leader', 'リーダー')], max_length=10)),
                ('question1', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (None, 'わからない')])),
                ('question2', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (None, 'わからない')])),
                ('question3', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (None, 'わからない')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
