# Generated by Django 5.1.6 on 2025-03-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_answer_question1_alter_answer_question2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question1',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question2',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question3',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reviewee_role',
            field=models.CharField(choices=[('一般', '一般'), ('リーダー', 'リーダー'), ('マネージャー', 'マネージャー')], max_length=50),
        ),
    ]
