# Generated by Django 5.1.6 on 2025-03-16 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_answer_question1_alter_answer_question2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='reviewer_name',
        ),
        migrations.AlterField(
            model_name='answer',
            name='reviewee_role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
