# Generated by Django 5.1.6 on 2025-03-16 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_answer_reviewer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reviewer_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='reviewee_role',
            field=models.CharField(choices=[('一般', '一般'), ('リーダー', 'リーダー'), ('マネージャー', 'マネージャー')], max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
