# Generated by Django 5.1.6 on 2025-03-16 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_answer_reviewer_name_alter_answer_reviewee_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='reviewee_role',
            field=models.CharField(choices=[('general', '一般'), ('manager', 'マネージャー'), ('leader', 'リーダー')], max_length=50),
        ),
    ]
